Modules list:
-------------
earthspin.o:
    CODE              Offs=000000  Size=000374  Align=00001  Fill=0000
    RODATA            Offs=000000  Size=00007F  Align=00001  Fill=0000
bitmap_clear.o:
    CODE              Offs=000374  Size=000024  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_directerrno.o):
    CODE              Offs=000398  Size=000009  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_file.o):
    DATA              Offs=000000  Size=00001E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_hextab.o):
    RODATA            Offs=00007F  Size=000010  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_longminstr.o):
    RODATA            Offs=00008F  Size=00000C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_mappederrno.o):
    CODE              Offs=0003A1  Size=00000F  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_oserror.o):
    BSS               Offs=000000  Size=000001  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_printf.o):
    CODE              Offs=0003B0  Size=0003A1  Align=00001  Fill=0000
    BSS               Offs=000001  Size=00002B  Align=00001  Fill=0000
    DATA              Offs=00001E  Size=000003  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(_seterrno.o):
    CODE              Offs=000751  Size=000009  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(addysp.o):
    CODE              Offs=00075A  Size=00000E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(and.o):
    CODE              Offs=000768  Size=00000F  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(aslax3.o):
    CODE              Offs=000777  Size=00000E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(axlong.o):
    CODE              Offs=000785  Size=00000D  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(callmain.o):
    CODE              Offs=000792  Size=000017  Align=00001  Fill=0000
    DATA              Offs=000021  Size=000004  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(checkferror.o):
    CODE              Offs=0007A9  Size=00000C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(condes.o):
    CODE              Offs=0007B5  Size=00000C  Align=00001  Fill=0000
    DATA              Offs=000025  Size=000025  Align=00001  Fill=0000
    ONCE              Offs=000000  Size=00000C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(crt0.o):
    STARTUP           Offs=000000  Size=000021  Align=00001  Fill=0000
    ONCE              Offs=00000C  Size=00001B  Align=00001  Fill=0000
    INIT              Offs=000000  Size=000002  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(ctype.o):
    RODATA            Offs=00009B  Size=00008B  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(ctypemask.o):
    CODE              Offs=0007C1  Size=00001E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(decsp4.o):
    CODE              Offs=0007DF  Size=00000D  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(decsp6.o):
    CODE              Offs=0007EC  Size=00000D  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(eq.o):
    CODE              Offs=0007F9  Size=00000A  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(errno.o):
    BSS               Offs=00002C  Size=000002  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(exehdr.o):
    EXEHDR            Offs=000000  Size=00000C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(filedes.o):
    CODE              Offs=000803  Size=00000E  Align=00001  Fill=0000
    DATA              Offs=00004A  Size=000010  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(fputc.o):
    CODE              Offs=000811  Size=000047  Align=00001  Fill=0000
    BSS               Offs=00002E  Size=000002  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(fwrite.o):
    CODE              Offs=000858  Size=000077  Align=00001  Fill=0000
    BSS               Offs=000030  Size=000002  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(icmp.o):
    CODE              Offs=0008CF  Size=00002E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(incsp1.o):
    CODE              Offs=0008FD  Size=000007  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(incsp2.o):
    CODE              Offs=000904  Size=000015  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(incsp3.o):
    CODE              Offs=000919  Size=000005  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(incsp6.o):
    CODE              Offs=00091E  Size=000005  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(kernal.o):
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(ladd.o):
    CODE              Offs=000923  Size=000024  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(ldaxsp.o):
    CODE              Offs=000947  Size=000009  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(ldeaxysp.o):
    CODE              Offs=000950  Size=000013  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(linc.o):
    CODE              Offs=000963  Size=000011  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(lneg.o):
    CODE              Offs=000974  Size=00001E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(loadaddr.o):
    LOADADDR          Offs=000000  Size=000002  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(lpush.o):
    CODE              Offs=000992  Size=00001E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(ltoa.o):
    CODE              Offs=0009B0  Size=000093  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(makebool.o):
    CODE              Offs=000A43  Size=00002C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(mul.o):
    CODE              Offs=000A6F  Size=000045  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(mul8.o):
    CODE              Offs=000AB4  Size=00003A  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(or.o):
    CODE              Offs=000AEE  Size=000011  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(oserror.o):
    CODE              Offs=000AFF  Size=000016  Align=00001  Fill=0000
    RODATA            Offs=000126  Size=00005A  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(popa.o):
    CODE              Offs=000B15  Size=00000A  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(popptr1.o):
    CODE              Offs=000B1F  Size=00000E  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(printf.o):
    CODE              Offs=000B2D  Size=000033  Align=00001  Fill=0000
    BSS               Offs=000032  Size=000001  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(push1.o):
    CODE              Offs=000B60  Size=000005  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(pusha.o):
    CODE              Offs=000B65  Size=000016  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(pushax.o):
    CODE              Offs=000B7B  Size=00001A  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(pushptr1.o):
    CODE              Offs=000B95  Size=000007  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(pushwsp.o):
    CODE              Offs=000B9C  Size=00001C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(putchar.o):
    CODE              Offs=000BB8  Size=00000C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(puts.o):
    CODE              Offs=000BC4  Size=000063  Align=00001  Fill=0000
    DATA              Offs=00005A  Size=000001  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(returnFFFF.o):
    CODE              Offs=000C27  Size=000004  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(rwcommon.o):
    CODE              Offs=000C2B  Size=00001A  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(shreax1.o):
    CODE              Offs=000C45  Size=00000C  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(shreax4.o):
    CODE              Offs=000C51  Size=000011  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(staxsp.o):
    CODE              Offs=000C62  Size=00000B  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(steaxsp.o):
    CODE              Offs=000C6D  Size=000015  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(strlen.o):
    CODE              Offs=000C82  Size=000016  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(strlower.o):
    CODE              Offs=000C98  Size=000027  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(udiv.o):
    CODE              Offs=000CBF  Size=00004F  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(vaddr0.o):
    CODE              Offs=000D0E  Size=00000F  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(vfprintf.o):
    CODE              Offs=000D1D  Size=000060  Align=00001  Fill=0000
    DATA              Offs=00005B  Size=000008  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(vpeek.o):
    CODE              Offs=000D7D  Size=000009  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(vpoke.o):
    CODE              Offs=000D86  Size=00000A  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(write.o):
    CODE              Offs=000D90  Size=000052  Align=00001  Fill=0000
    ONCE              Offs=000027  Size=000011  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(zerobss.o):
    CODE              Offs=000DE2  Size=000023  Align=00001  Fill=0000
C:\Users\ed\Desktop\x16\cc65\lib/cx16.lib(zeropage.o):
    ZEROPAGE          Offs=000000  Size=00001A  Align=00001  Fill=0000


Segment list:
-------------
Name                   Start     End    Size  Align
----------------------------------------------------
ZEROPAGE              000022  00003B  00001A  00001
LOADADDR              0007FF  000800  000002  00001
EXEHDR                000801  00080C  00000C  00001
STARTUP               00080D  00082D  000021  00001
CODE                  00082E  001632  000E05  00001
RODATA                001633  0017B2  000180  00001
DATA                  0017B3  001815  000063  00001
INIT                  001816  001817  000002  00001
BSS                   001818  00184A  000033  00001
ONCE                  001818  001851  00003A  00001


Exports list by name:
---------------------
BSOUT                     00FFD2 RLA    CHROUT                    00FFD2 RLA    
CKOUT                     00FFC9 RLA    CLRCH                     00FFCC RLA    
OPEN                      00FFC0 RLA    READST                    00FFB7 RLA    
SETLFS                    00FFBA RLA    __BSS_RUN__               001818 RLA    
__BSS_SIZE__              000033 REA    __CONSTRUCTOR_COUNT__     000001 REA    
__CONSTRUCTOR_TABLE__     001850 RLA    __DESTRUCTOR_COUNT__      000000 REA    
__DESTRUCTOR_TABLE__      0017B3 RLA    __EXEHDR__                000001 REA    
__HEADER_LAST__           00080D RLA    __HIMEM__                 009F00 REA    
__LOADADDR__              000001 REA    __MAIN_SIZE__             0096F3 REA    
__MAIN_START__            00080D RLA    __ONCE_RUN__              001818 RLA    
__STACKSIZE__             000800 REA    __STARTUP__               000001 REA    
___directerrno            000BC6 RLA    ___errno                  001844 RLA    
___mappederrno            000BCF RLA    ___oserror                001818 RLA    
___osmaperrno             00132D RLA    ___seterrno               000F7F RLA    
__ctype                   0016CE RLA    __ctypeidx                0016D9 RLA    
__hextab                  0016B2 RLA    __longminstr              0016C2 RLA    
__printf                  000CCF RLA    _fputc                    00103F RLA    
_fwrite                   001086 RLA    _ltoa                     0011F6 RLA    
_main                     000BA1 RLA    _printf                   00135B RLA    
_putchar                  0013E6 RLA    _puts                     0013F2 RLA    
_stdout                   0017CD RLA    _strlen                   0014B0 RLA    
_strlower                 0014C6 RLA    _ultoa                    001235 RLA    
_vfprintf                 001582 RLA    _vpeek                    0015AB RLA    
_vpoke                    0015B4 RLA    _write                    0015BE RLA    
addysp                    000F89 RLA    addysp1                   000F88 RLA    
aslax3                    000FA5 RLA    axlong                    000FB3 RLA    
axulong                   000FB9 RLA    booleq                    001277 RLA    
boolne                    001271 RLA    boolult                   001290 RLA    
callmain                  000FC0 RLA    checkferror               000FD7 RLA    
ctypemaskdirect           000FF3 RLA    decsp4                    00100D RLA    
decsp6                    00101A RLA    donelib                   000FE3 RLA    
fdtab                     0017FD RLA    inceaxy                   001191 RLA    
incsp1                    00112B RLA    incsp2                    001139 RLA    
incsp3                    001147 RLA    incsp6                    00114C RLA    
initlib                   001818 RLA    initstdout                00183F  LAI   
ldaxysp                   001177 RLA    ldeaxysp                  001180 RLA    
mul8x16                   0012E4 RLA    mul8x16a                  0012EE RLA    
negeax                    0011A2 RLA    popa                      001343 RLA    
popax                     001132 RLA    popptr1                   00134D RLA    
ptr1                      00002A RLZ    ptr2                      00002C RLZ    
ptr3                      00002E RLZ    ptr4                      000030 RLZ    
push1                     00138E RLA    pusha                     001397 RLA    
pusha0                    0013AB RLA    pushax                    0013AD RLA    
pusheax                   0011C7 RLA    pushptr1                  0013C3 RLA    
pushwysp                  0013CC RLA    regbank                   000036 RLZ    
returnFFFF                001455 RLA    rwcommon                  001459 RLA    
shreax1                   001473 RLA    shreax4                   00147F RLA    
sp                        000022 RLZ    sreg                      000024 RLZ    
staxysp                   001492 RLA    steaxysp                  00149D RLA    
tmp1                      000032 RLZ    tmp2                      000033 RLZ    
tosaddeax                 001157 RLA    tosandax                  000F98 RLA    
toseqax                   00102B RLA    tosicmp                   0010FF RLA    
tosorax                   00131E RLA    tosudivax                 0014EF RLA    
tosumulax                 00129D RLA    vaddr0                    00153C RLA    
zerobss                   001610 RLA    


Exports list by value:
----------------------
__DESTRUCTOR_COUNT__      000000 REA    __STARTUP__               000001 REA    
__EXEHDR__                000001 REA    __LOADADDR__              000001 REA    
__CONSTRUCTOR_COUNT__     000001 REA    sp                        000022 RLZ    
sreg                      000024 RLZ    ptr1                      00002A RLZ    
ptr2                      00002C RLZ    ptr3                      00002E RLZ    
ptr4                      000030 RLZ    tmp1                      000032 RLZ    
__BSS_SIZE__              000033 REA    tmp2                      000033 RLZ    
regbank                   000036 RLZ    __STACKSIZE__             000800 REA    
__MAIN_START__            00080D RLA    __HEADER_LAST__           00080D RLA    
_main                     000BA1 RLA    ___directerrno            000BC6 RLA    
___mappederrno            000BCF RLA    __printf                  000CCF RLA    
___seterrno               000F7F RLA    addysp1                   000F88 RLA    
addysp                    000F89 RLA    tosandax                  000F98 RLA    
aslax3                    000FA5 RLA    axlong                    000FB3 RLA    
axulong                   000FB9 RLA    callmain                  000FC0 RLA    
checkferror               000FD7 RLA    donelib                   000FE3 RLA    
ctypemaskdirect           000FF3 RLA    decsp4                    00100D RLA    
decsp6                    00101A RLA    toseqax                   00102B RLA    
_fputc                    00103F RLA    _fwrite                   001086 RLA    
tosicmp                   0010FF RLA    incsp1                    00112B RLA    
popax                     001132 RLA    incsp2                    001139 RLA    
incsp3                    001147 RLA    incsp6                    00114C RLA    
tosaddeax                 001157 RLA    ldaxysp                   001177 RLA    
ldeaxysp                  001180 RLA    inceaxy                   001191 RLA    
negeax                    0011A2 RLA    pusheax                   0011C7 RLA    
_ltoa                     0011F6 RLA    _ultoa                    001235 RLA    
boolne                    001271 RLA    booleq                    001277 RLA    
boolult                   001290 RLA    tosumulax                 00129D RLA    
mul8x16                   0012E4 RLA    mul8x16a                  0012EE RLA    
tosorax                   00131E RLA    ___osmaperrno             00132D RLA    
popa                      001343 RLA    popptr1                   00134D RLA    
_printf                   00135B RLA    push1                     00138E RLA    
pusha                     001397 RLA    pusha0                    0013AB RLA    
pushax                    0013AD RLA    pushptr1                  0013C3 RLA    
pushwysp                  0013CC RLA    _putchar                  0013E6 RLA    
_puts                     0013F2 RLA    returnFFFF                001455 RLA    
rwcommon                  001459 RLA    shreax1                   001473 RLA    
shreax4                   00147F RLA    staxysp                   001492 RLA    
steaxysp                  00149D RLA    _strlen                   0014B0 RLA    
_strlower                 0014C6 RLA    tosudivax                 0014EF RLA    
vaddr0                    00153C RLA    _vfprintf                 001582 RLA    
_vpeek                    0015AB RLA    _vpoke                    0015B4 RLA    
_write                    0015BE RLA    zerobss                   001610 RLA    
__hextab                  0016B2 RLA    __longminstr              0016C2 RLA    
__ctype                   0016CE RLA    __ctypeidx                0016D9 RLA    
__DESTRUCTOR_TABLE__      0017B3 RLA    _stdout                   0017CD RLA    
fdtab                     0017FD RLA    __BSS_RUN__               001818 RLA    
___oserror                001818 RLA    initlib                   001818 RLA    
__ONCE_RUN__              001818 RLA    initstdout                00183F  LAI   
___errno                  001844 RLA    __CONSTRUCTOR_TABLE__     001850 RLA    
__MAIN_SIZE__             0096F3 REA    __HIMEM__                 009F00 REA    
READST                    00FFB7 RLA    SETLFS                    00FFBA RLA    
OPEN                      00FFC0 RLA    CKOUT                     00FFC9 RLA    
CLRCH                     00FFCC RLA    CHROUT                    00FFD2 RLA    
BSOUT                     00FFD2 RLA    


Imports list:
-------------
BSOUT (kernal.o):
    write.o                   cbm/cbm.inc:49
CHROUT (kernal.o):
    crt0.o                    cx16/crt0.s:10
CKOUT (kernal.o):
    write.o                   cbm/cbm.inc:45
CLRCH (kernal.o):
    write.o                   cbm/cbm.inc:46
OPEN (kernal.o):
    write.o                   cbm/cbm.inc:35
READST (kernal.o):
    write.o                   cbm/cbm.inc:32
SETLFS (kernal.o):
    write.o                   cbm/cbm.inc:33
__BSS_RUN__ ([linker generated]):
    zerobss.o                 common/zerobss.s:8
__BSS_SIZE__ ([linker generated]):
    zerobss.o                 common/zerobss.s:8
__CONSTRUCTOR_COUNT__ ([linker generated]):
    condes.o                  runtime/condes.s:18
__CONSTRUCTOR_TABLE__ ([linker generated]):
    condes.o                  runtime/condes.s:18
__DESTRUCTOR_COUNT__ ([linker generated]):
    condes.o                  runtime/condes.s:19
__DESTRUCTOR_TABLE__ ([linker generated]):
    condes.o                  runtime/condes.s:19
__EXEHDR__ (exehdr.o):
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:6
__HEADER_LAST__ ([linker generated]):
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:14
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:14
__HIMEM__ ([linker generated]):
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:15
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:14
__LOADADDR__ (loadaddr.o):
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:5
__MAIN_SIZE__ ([linker generated]):
    crt0.o                    cx16/crt0.s:11
__MAIN_START__ ([linker generated]):
    crt0.o                    cx16/crt0.s:11
__ONCE_RUN__ ([linker generated]):
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:15
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:15
__STACKSIZE__ ([linker generated]):
    [linker generated]        C:\Users\ed\Desktop\x16\cc65\cfg/cx16.cfg:15
__STARTUP__ (crt0.o):
    earthspin.o               build/earthspin.s:13
___directerrno (_directerrno.o):
    write.o                   /home/runner/work/cc65/cc65/asminc/errno.inc:10
___errno (errno.o):
    _seterrno.o               /home/runner/work/cc65/cc65/asminc/errno.inc:7
___mappederrno (_mappederrno.o):
    write.o                   /home/runner/work/cc65/cc65/asminc/errno.inc:10
___oserror (_oserror.o):
    _mappederrno.o            /home/runner/work/cc65/cc65/asminc/errno.inc:7
    _directerrno.o            /home/runner/work/cc65/cc65/asminc/errno.inc:7
    write.o                   /home/runner/work/cc65/cc65/asminc/errno.inc:7
___osmaperrno (oserror.o):
    _mappederrno.o            /home/runner/work/cc65/cc65/asminc/errno.inc:8
___seterrno (_seterrno.o):
    fwrite.o                  /home/runner/work/cc65/cc65/asminc/errno.inc:9
    _mappederrno.o            /home/runner/work/cc65/cc65/asminc/errno.inc:9
    _directerrno.o            /home/runner/work/cc65/cc65/asminc/errno.inc:9
__ctype (ctype.o):
    ctypemask.o               common/ctypemask.s:23
__ctypeidx (ctype.o):
    ctypemask.o               common/ctypemask.s:24
__hextab (_hextab.o):
    ltoa.o                    common/ltoa.s:10
__longminstr (_longminstr.o):
    ltoa.o                    common/ltoa.s:10
__printf (_printf.o):
    vfprintf.o                common/vfprintf.s:10
_fputc (fputc.o):
    putchar.o                 common/putchar.s:10
_fwrite (fwrite.o):
    vfprintf.o                common/vfprintf.s:10
_ltoa (ltoa.o):
    _printf.o                 common/_printf.s:12
_main (earthspin.o):
    callmain.o                runtime/callmain.s:11
_printf (printf.o):
    earthspin.o               build/earthspin.s:17
_putchar (putchar.o):
    earthspin.o               build/earthspin.s:18
_puts (puts.o):
    earthspin.o               build/earthspin.s:19
_stdout (_file.o):
    puts.o                    ../libwrk/cx16/puts.s:19
    putchar.o                 common/putchar.s:9
    printf.o                  common/printf.s:8
_strlen (strlen.o):
    _printf.o                 common/_printf.s:13
    puts.o                    ../libwrk/cx16/puts.s:21
    earthspin.o               build/earthspin.s:14
_strlower (strlower.o):
    _printf.o                 common/_printf.s:13
_ultoa (ltoa.o):
    _printf.o                 common/_printf.s:12
_vfprintf (vfprintf.o):
    printf.o                  common/printf.s:8
_vpeek (vpeek.o):
    earthspin.o               build/earthspin.s:15
_vpoke (vpoke.o):
    earthspin.o               build/earthspin.s:16
_write (write.o):
    fwrite.o                  common/fwrite.s:10
    fputc.o                   common/fputc.s:9
    puts.o                    ../libwrk/cx16/puts.s:22
addysp (addysp.o):
    fwrite.o                  common/fwrite.s:11
    printf.o                  common/printf.s:8
    incsp6.o                  runtime/incsp6.s:8
    incsp3.o                  runtime/incsp3.s:8
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
addysp1 (addysp.o):
    or.o                      runtime/or.s:9
    ladd.o                    runtime/ladd.s:8
    and.o                     runtime/and.s:8
aslax3 (aslax3.o):
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
axlong (axlong.o):
    _printf.o                 common/_printf.s:11
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
axulong (axlong.o):
    _printf.o                 common/_printf.s:11
    earthspin.o               build/earthspin.s:528
booleq (makebool.o):
    eq.o                      runtime/eq.s:8
boolne (makebool.o):
    earthspin.o               build/earthspin.s:528
boolult (makebool.o):
    earthspin.o               build/earthspin.s:528
callmain (callmain.o):
    crt0.o                    cx16/crt0.s:9
checkferror (checkferror.o):
    fputc.o                   common/fputc.s:9
ctypemaskdirect (ctypemask.o):
    strlower.o                common/strlower.s:14
decsp4 (decsp4.o):
    lpush.o                   runtime/lpush.s:12
    earthspin.o               build/earthspin.s:528
decsp6 (decsp6.o):
    _printf.o                 common/_printf.s:11
donelib (condes.o):
    crt0.o                    cx16/crt0.s:8
fdtab (filedes.o):
    write.o                   cbm/filedes.inc:7
inceaxy (linc.o):
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
incsp1 (incsp1.o):
    earthspin.o               build/earthspin.s:528
incsp2 (incsp2.o):
    popptr1.o                 runtime/popptr1.s:8
    fputc.o                   common/fputc.s:10
    puts.o                    ../libwrk/cx16/puts.s:93
incsp3 (incsp3.o):
    earthspin.o               build/earthspin.s:528
incsp6 (incsp6.o):
    fwrite.o                  common/fwrite.s:11
    vfprintf.o                common/vfprintf.s:9
    earthspin.o               build/earthspin.s:528
initlib (condes.o):
    crt0.o                    cx16/crt0.s:8
ldaxysp (ldaxsp.o):
    fwrite.o                  common/fwrite.s:11
    puts.o                    ../libwrk/cx16/puts.s:93
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
ldeaxysp (ldeaxysp.o):
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
mul8x16 (mul8.o):
    mul.o                     runtime/mul.s:8
mul8x16a (mul8.o):
    mul.o                     runtime/mul.s:8
negeax (lneg.o):
    ltoa.o                    common/ltoa.s:9
popa (popa.o):
    vpoke.o                   cx16/vpoke.s:12
popax (incsp2.o):
    rwcommon.o                cbm/rwcommon.s:9
    ltoa.o                    common/ltoa.s:9
    fputc.o                   common/fputc.s:10
    _printf.o                 common/_printf.s:11
popptr1 (popptr1.o):
    udiv.o                    runtime/udiv.s:9
    rwcommon.o                cbm/rwcommon.s:9
    mul8.o                    runtime/mul8.s:9
    mul.o                     runtime/mul.s:9
    ltoa.o                    common/ltoa.s:9
    fputc.o                   common/fputc.s:11
ptr1 (zeropage.o):
    checkferror.o             common/checkferror.s:12
    udiv.o                    runtime/udiv.s:10
    strlower.o                common/strlower.s:13
    pushptr1.o                runtime/pushptr1.s:9
    popptr1.o                 runtime/popptr1.s:9
    mul8.o                    runtime/mul8.s:10
    mul.o                     runtime/mul.s:10
    ltoa.o                    common/ltoa.s:11
    fwrite.o                  common/fwrite.s:14
    fputc.o                   common/fputc.s:8
    _printf.o                 /home/runner/work/cc65/cc65/asminc/zeropage.inc:12
    zerobss.o                 common/zerobss.s:9
    write.o                   cbm/write.s:11
    vfprintf.o                common/vfprintf.s:11
    puts.o                    ../libwrk/cx16/puts.s:11
    printf.o                  common/printf.s:9
ptr2 (zeropage.o):
    strlower.o                common/strlower.s:13
    rwcommon.o                cbm/rwcommon.s:10
    ltoa.o                    common/ltoa.s:11
    _printf.o                 /home/runner/work/cc65/cc65/asminc/zeropage.inc:12
    write.o                   cbm/write.s:11
ptr3 (zeropage.o):
    rwcommon.o                cbm/rwcommon.s:10
    ltoa.o                    common/ltoa.s:11
    write.o                   cbm/write.s:11
ptr4 (zeropage.o):
    udiv.o                    runtime/udiv.s:10
    mul8.o                    runtime/mul8.s:10
    mul.o                     runtime/mul.s:10
    strlen.o                  common/strlen.s:12
    linc.o                    runtime/linc.s:8
push1 (push1.o):
    _printf.o                 common/_printf.s:11
    vfprintf.o                common/vfprintf.s:9
pusha (pusha.o):
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
pusha0 (pushax.o):
    push1.o                   runtime/push1.s:8
    fwrite.o                  common/fwrite.s:11
    fputc.o                   common/fputc.s:10
    puts.o                    ../libwrk/cx16/puts.s:93
pushax (pushax.o):
    pushptr1.o                runtime/pushptr1.s:8
    fwrite.o                  common/fwrite.s:11
    fputc.o                   common/fputc.s:10
    callmain.o                runtime/callmain.s:11
    _printf.o                 common/_printf.s:11
    puts.o                    ../libwrk/cx16/puts.s:93
    putchar.o                 common/putchar.s:8
    printf.o                  common/printf.s:8
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
pusheax (lpush.o):
    _printf.o                 common/_printf.s:11
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
pushptr1 (pushptr1.o):
    fputc.o                   common/fputc.s:11
pushwysp (pushwsp.o):
    fwrite.o                  common/fwrite.s:11
    vfprintf.o                common/vfprintf.s:9
    puts.o                    ../libwrk/cx16/puts.s:93
regbank (zeropage.o):
    _printf.o                 /home/runner/work/cc65/cc65/asminc/zeropage.inc:14
    earthspin.o               build/earthspin.s:10
returnFFFF (returnFFFF.o):
    fputc.o                   common/fputc.s:11
rwcommon (rwcommon.o):
    write.o                   cbm/write.s:10
shreax1 (shreax1.o):
    earthspin.o               build/earthspin.s:528
shreax4 (shreax4.o):
    earthspin.o               build/earthspin.s:528
sp (zeropage.o):
    pushwsp.o                 runtime/pushwsp.s:8
    popptr1.o                 runtime/popptr1.s:9
    popa.o                    runtime/popa.s:8
    incsp2.o                  runtime/incsp2.s:8
    decsp6.o                  runtime/decsp6.s:8
    _printf.o                 /home/runner/work/cc65/cc65/asminc/zeropage.inc:11
    vfprintf.o                common/vfprintf.s:11
    steaxsp.o                 runtime/steaxsp.s:8
    staxsp.o                  runtime/staxsp.s:8
    pushax.o                  runtime/pushax.s:8
    pusha.o                   runtime/pusha.s:8
    printf.o                  common/printf.s:9
    or.o                      runtime/or.s:10
    lpush.o                   runtime/lpush.s:13
    ldeaxysp.o                runtime/ldeaxysp.s:12
    ldaxsp.o                  runtime/ldaxsp.s:8
    ladd.o                    runtime/ladd.s:9
    incsp1.o                  runtime/incsp1.s:8
    icmp.o                    runtime/icmp.s:9
    decsp4.o                  runtime/decsp4.s:8
    crt0.o                    /home/runner/work/cc65/cc65/asminc/zeropage.inc:11
    and.o                     runtime/and.s:9
    addysp.o                  runtime/addysp.s:8
    earthspin.o               build/earthspin.s:10
sreg (zeropage.o):
    lneg.o                    runtime/lneg.s:11
    vaddr0.o                  cx16/vaddr0.s:10
    udiv.o                    runtime/udiv.s:10
    ltoa.o                    common/ltoa.s:11
    _printf.o                 /home/runner/work/cc65/cc65/asminc/zeropage.inc:11
    steaxsp.o                 runtime/steaxsp.s:8
    shreax4.o                 runtime/shreax4.s:8
    shreax1.o                 runtime/shreax1.s:8
    lpush.o                   runtime/lpush.s:13
    linc.o                    runtime/linc.s:8
    ldeaxysp.o                runtime/ldeaxysp.s:12
    ladd.o                    runtime/ladd.s:9
    icmp.o                    runtime/icmp.s:9
    axlong.o                  runtime/axlong.s:9
    earthspin.o               build/earthspin.s:10
staxysp (staxsp.o):
    earthspin.o               build/earthspin.s:528
steaxysp (steaxsp.o):
    earthspin.o               build/earthspin.s:528
tmp1 (zeropage.o):
    mul.o                     runtime/mul.s:10
    ltoa.o                    common/ltoa.s:11
    _printf.o                 /home/runner/work/cc65/cc65/asminc/zeropage.inc:13
    shreax4.o                 runtime/shreax4.s:8
    shreax1.o                 runtime/shreax1.s:8
    or.o                      runtime/or.s:10
    ladd.o                    runtime/ladd.s:9
    aslax3.o                  runtime/aslax3.s:8
    earthspin.o               build/earthspin.s:11
tmp2 (zeropage.o):
    rwcommon.o                cbm/rwcommon.s:10
tosaddeax (ladd.o):
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
    earthspin.o               build/earthspin.s:528
tosandax (and.o):
    earthspin.o               build/earthspin.s:528
toseqax (eq.o):
    earthspin.o               build/earthspin.s:528
tosicmp (icmp.o):
    eq.o                      runtime/eq.s:8
tosorax (or.o):
    earthspin.o               build/earthspin.s:528
tosudivax (udiv.o):
    fwrite.o                  common/fwrite.s:12
tosumulax (mul.o):
    fwrite.o                  common/fwrite.s:12
vaddr0 (vaddr0.o):
    vpoke.o                   cx16/vpoke.s:12
    vpeek.o                   cx16/vpeek.s:10
zerobss (zerobss.o):
    crt0.o                    cx16/crt0.s:9

